export const UPDATE_MOVEMENT = "UPDATE_MOVEMENT";
export const UPDATE_ACTION = "UPDATE_ACTION";
export const UPDATE_BONUS_ACTION = "UPDATE_BONUS_ACTION";
export const UPDATE_SELECTED_MOVES = "UPDATE_SELECTED_MOVES";
export const UNDO_LAST_MOVE = "UNDO_LAST_MOVE";
export const CLEAR_MOVES = "CLEAR_MOVES";

/** Character Action Types */
export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
